/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import Controlador.ControladorVentanaSillas;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelo.Persona;
import modelo.Silla;

/**
 *
 * @author HP
 */
public class VentanaGestionPersona extends javax.swing.JFrame {

    VentanaSillas ventSillas;
    Silla silla;
    ControladorVentanaSillas controladorVS;

    /**
     * Creates new form VentanaGestionPersona
     */
    public VentanaGestionPersona(VentanaSillas ventSilla, Silla silla) {
        initComponents();
        setLocationRelativeTo(this);
        this.ventSillas = ventSilla;
        this.silla = silla;
        controladorVS = ventSillas.getControladorSilla();
        validarVentana();

    }

    private void validarVentana() {
        if (silla.isEstado()) {
            btnAgregar.setVisible(true);
            btnModificar.setVisible(false);
            btnEliminar.setVisible(false);
            txtCedula.setEnabled(true);
            limpiarCampos();
        } else {
            btnAgregar.setVisible(false);
            btnModificar.setVisible(true);
            btnEliminar.setVisible(true);
            txtNombre.setText(silla.getPersona().getNombre());
            txtCedula.setText(silla.getPersona().getCedula());
            txtEmail.setText(silla.getPersona().getEmail());
            txtDireccion.setText(silla.getPersona().getDireccion());
            txtCedula.setEnabled(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        GestionarPersona = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCedula = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        GestionarPersona.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Gestion Persona", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI Black", 0, 18))); // NOI18N

        jLabel1.setText("Nombre:");

        jLabel3.setText("Direccion:");

        jLabel4.setText("Cedula:");

        txtNombre.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtDireccion.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        txtCedula.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel5.setText("Email");

        txtEmail.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout GestionarPersonaLayout = new javax.swing.GroupLayout(GestionarPersona);
        GestionarPersona.setLayout(GestionarPersonaLayout);
        GestionarPersonaLayout.setHorizontalGroup(
            GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionarPersonaLayout.createSequentialGroup()
                .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GestionarPersonaLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, GestionarPersonaLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(55, 55, 55))
                            .addGroup(GestionarPersonaLayout.createSequentialGroup()
                                .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(49, 49, 49))))
                    .addGroup(GestionarPersonaLayout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(btnAgregar)
                        .addGap(39, 39, 39)))
                .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(txtCedula, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                        .addComponent(txtDireccion)
                        .addComponent(txtEmail)
                        .addComponent(txtNombre))
                    .addGroup(GestionarPersonaLayout.createSequentialGroup()
                        .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnVolver, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnModificar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)))
                .addContainerGap(62, Short.MAX_VALUE))
        );
        GestionarPersonaLayout.setVerticalGroup(
            GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(GestionarPersonaLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtCedula, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(GestionarPersonaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAgregar)
                    .addComponent(btnModificar)
                    .addComponent(btnEliminar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                .addComponent(btnVolver)
                .addGap(33, 33, 33))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GestionarPersona, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(GestionarPersona, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        // TODO add your handling code here:

        String nombre = txtNombre.getText();
        String email = txtEmail.getText();
        String direccion = txtDireccion.getText();
        String cedula = txtCedula.getText();

        Persona aux = controladorVS.buscarPersona(cedula);
        if (aux != null) {
            JOptionPane.showMessageDialog(null, "Ya se encuentra una persona registrada con esta cedula");

        } else {
            Persona persona = new Persona(nombre, email, direccion, cedula);
            boolean respuesta = controladorVS.agregarPersona(persona, silla);
            if (respuesta) {
                JOptionPane.showMessageDialog(null, "Se ha registrado correctamente");

            }
        }
        limpiarCampos();

    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        // TODO add your handling code here:

        String nombre = txtNombre.getText();
        String email = txtEmail.getText();
        String direccion = txtDireccion.getText();
        String cedula = txtCedula.getText();

        Persona persona = new Persona(nombre, email, direccion, cedula);
        Persona modificar = controladorVS.modificarPersona(cedula);
        if (modificar != null) {
            modificar.setNombre(nombre);
            modificar.setEmail(email);
            modificar.setDireccion(direccion);

            JOptionPane.showMessageDialog(null, "La Persona se ha modificado: "
                    + "\n Nombre: " + persona.getNombre()
                    + "\n Email: " + persona.getEmail() + "\n Direccion: " + persona.getDireccion());
            silla.setPersona(modificar);
            controladorVS.escritorSerializar();
        } else {
            JOptionPane.showMessageDialog(null, "NO se ha podido modificar");
        }

        limpiarCampos();


    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        // TODO add your handling code here:

        String cedula = txtCedula.getText();

        boolean eliminar = controladorVS.eliminarPersona(cedula);
        if (eliminar) {
            JOptionPane.showMessageDialog(null, "Se ha elimnado corretamente la persona");
        } else {
            JOptionPane.showMessageDialog(null, "No se puedo eliminar, vuelva a intentarlo");

        }
        limpiarCampos();

    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        // TODO add your handling code here:

        ventSillas.validarPosiciones();
        ventSillas.setVisible(true);
        this.dispose();
        ventSillas.limpiarCamposVer();
    }//GEN-LAST:event_btnVolverActionPerformed
    private void limpiarCampos() {
        txtNombre.setText("");
        txtEmail.setText("");
        txtDireccion.setText("");
        txtCedula.setText("");
    }



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel GestionarPersona;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField txtCedula;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
